language: c

compiler: gcc

env:
    global:
        - SANITYCHECK_OPTIONS=" --inline-logs -N --retry-failed 3 -v "
        - MATRIX_BUILDS="10"
        - ZEPHYR_TOOLCHAIN_VARIANT="zephyr"
        - ZEPHYR_SDK_INSTALL_DIR=/opt/sdk/zephyr-sdk-0.11.3
    matrix:
        - MATRIX_BUILD="1"
        - MATRIX_BUILD="2"
        - MATRIX_BUILD="3"
        - MATRIX_BUILD="4"
        - MATRIX_BUILD="5"
        - MATRIX_BUILD="6"
        - MATRIX_BUILD="7"
        - MATRIX_BUILD="8"
        - MATRIX_BUILD="9"
        - MATRIX_BUILD="10"

build:
    pre_ci_boot:
        image_name: zephyrprojectrtos/ci
        image_tag: v0.11.8
        pull: true
        options: "-e HOME=/home/buildslave --privileged=true --tty --net=bridge --user buildslave"

    ci:
      - git submodule update --remote
      - west init -l zephyr
      - west update
      - cd zephyr
      - TESTCOMMIT=`cat ${CREATE_TEST_COMMIT_STATE}/test_commit`;
      - git checkout ${TESTCOMMIT};
      - export QEMU_BIN_PATH=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/bin/
      - export QEMU_BIOS=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/share/qemu
      - export DTC=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/bin/dtc
      - source zephyr-env.sh
      - mkdir -p ../output/${TESTCOMMIT}
      - echo ${TESTCOMMIT} > ../output/${TESTCOMMIT}/commit.txt;
      - ./scripts/sanitycheck +../platforms.args --report-suffix ${TESTCOMMIT}-${MATRIX_BUILD} --subset ${MATRIX_BUILD}/${MATRIX_BUILDS} ${SANITYCHECK_OPTIONS};
    on_success:
      - mkdir -p ../shippable/testresults
      - >
        TESTCOMMIT=`git describe`;
        if [ -e ./sanity-out/sanitycheck_${TESTCOMMIT}-${MATRIX_BUILD}.xml ]; then
          cp ./sanity-out/sanitycheck.xml ../shippable/testresults/;
          export S3_PATH="s3://testing.zephyrproject.org/daily_tests";
          aws s3 cp ${S3_PATH}/versions.json .;
          grep -q ${TESTCOMMIT} versions.json || (cat versions.json | jq -r --arg TESTCOMMIT "$TESTCOMMIT" '. |= .+ [$TESTCOMMIT]' > out.json);
          cp ./sanity-out/*.xml  ../output/${TESTCOMMIT}/;
          rm -f ../output/${TESTCOMMIT}/sanitycheck*
          aws s3 sync ../output/ ${S3_PATH}/;
          if [ -f out.json ]; then
            aws s3 cp out.json ${S3_PATH}/versions.json;
          fi;
        fi;
    on_failure:
      - mkdir -p ../shippable/testresults
      - >
        TESTCOMMIT=`git describe`;
        if [ -e ./sanity-out/sanitycheck_${TESTCOMMIT}-${MATRIX_BUILD}.xml ]; then
          export S3_PATH="s3://testing.zephyrproject.org/daily_tests";
          cp ./sanity-out/sanitycheck.xml ../shippable/testresults/;
          aws s3 cp ${S3_PATH}/versions.json .;
          TESTCOMMIT=`git describe`;
          grep -q ${TESTCOMMIT} versions.json || cat versions.json | jq -r --arg TESTCOMMIT "$TESTCOMMIT" '. |= .+ [$TESTCOMMIT]' > out.json
          cp ./sanity-out/*.xml  ../output/${TESTCOMMIT}/;
          rm -f ../output/${TESTCOMMIT}/sanitycheck*
          aws s3 sync ../output/ ${S3_PATH}/
          if [ -f out.json ]; then
            aws s3 cp out.json ${S3_PATH}/versions.json;
          fi;
        fi;

integrations:
  generic:
    - integrationName: s3_testing
  notifications:
    - integrationName: slack_integration
      type: slack
      recipients:
        - "#ci"
      branches:
        only:
          - master
      on_success: never
      on_failure: always
    - integrationName: email
      type: email
      recipients:
        - builds+int+399+7809482394022958124@lists.zephyrproject.org
      branches:
        only:
          - master
      on_success: always
      on_failure: always
